#!/zsh

echo "==========Compare Exit Status================"
echo "          [correct]"
./pipex test/in "cat -e" "wc -l" test/out; echo -n "pipex status=$?\n"
< test/in cat -e | wc -l > test/out; echo -n "pipe  status=$?\n"
echo "          [wrong file1]"
./pipex XX "cat -e" "wc -l" test/out; echo -n "pipex status=$?\n"
< XX cat -e | wc -l > test/out; echo -n "pipe  status=$?\n"
echo "          [wrong cmd1]"
./pipex test/in "XX" "echo "salut"" test/out; echo -n "pipex status=$?\n"
< test/in XX; echo -n "pipe  status=$?\n"
echo "          [wrong cmd2]"
./pipex test/in "echo "salut"" "XX" test/out; echo -n "pipex status=$?\n"
< test/in echo "salut" | XX > test/out; echo -n "pipe  status=$?\n"
echo "============================================="
